ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['IMAGEGOAL_SENSOR']
  GOAL_SENSOR_UUID: imagegoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2
