# Note:  Hyperparameters have been changed slightly from
# the paper to allow for things to easily run on 1 GPU

BASE_TASK_CONFIG_PATH: "configs/tasks/pointnav_mp3d.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 1
TORCH_GPU_ID: 0
VIDEO_OPTION: []
# Can be uncommented to generate videos.
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "checkpoints/atc_real_pointnav_pretrain_resnet50_301_resume"
LOG_FILE: "checkpoints/atc_real_pointnav_pretrain_resnet50_301_resume"
VIDEO_DIR: "checkpoints/atc_real_pointnav_pretrain_resnet50_301_resume"
# Evaluate on all episodes
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "checkpoints/atc_real_pointnav_pretrain_resnet50_301_resume"
# This was 6 for mp3d and 8 for gibson in the paper
NUM_PROCESSES: 16
# Note:  To train the an RGB only model,
# you may need to use 8 processes with 4 mini batches,
# If so, the number of updates should be cut in half
SENSORS: ["RGB_SENSOR"]
CHECKPOINT_FOLDER: "checkpoints/atc_real_pointnav_pretrain_resnet50_301_resume"
NUM_UPDATES: 80001
LOG_INTERVAL: 50
CHECKPOINT_INTERVAL: 1000
RESUME_CURIOUS: ''
log_env: False

RL:
  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    # This was 4 in the paper
    num_mini_batch: 2
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    use_normalized_advantage: False
    reward_window_size: 50
    curiosity: True
    random: False
    rnd: False
    atc: True
    byol: False
    curiosity_reward: False
    RESUME_DETACH: False

UNSUP:
    CONTRASTIVE:
        updates: 5
