CHECKPOINT_FOLDER: "checkpoints_pointnav/baseline"
LOG_FILE: "checkpoints_pointnav/baseline"
TENSORBOARD_DIR: "checkpoints_pointnav/baseline"
VIDEO_DIR: "checkpoints_pointnav/baseline"

BASE_TASK_CONFIG_PATH: "configs/tasks/pointnav_mp3d.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 1
TORCH_GPU_ID: 0
VIDEO_OPTION: [] #["disk"] #"disk", "tensorboard"]
TEST_EPISODE_COUNT: 10
NUM_PROCESSES: 16
SENSORS: ["RGB_SENSOR"]
NUM_UPDATES: 80001 # -> 128M - we'd be happy w/ 3/5 -> 75M
LOG_INTERVAL: 50
CHECKPOINT_INTERVAL: 1000
RESUME_CURIOUS: ''
log_env: False
policy: False

RL:
  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 4
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    use_normalized_advantage: False
    reward_window_size: 50
    policy: "BASELINE"
    curiosity: False
    rnd: False
    byol: False
    random: False
    atc: False
    curious_reward: False
    RESUME_DETACH: False
    IMAGENET: False


UNSUP:
    CONTRASTIVE:
        updates: 0
